name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
  test:
    name: "Test for ESLint ${{ matrix.eslint }} on ${{ matrix.node }} OS: ${{matrix.os}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: [7, 8]
        node: [12, 14, 16, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install ESLint ${{ matrix.eslint }}
        run: |+
          npm i -D eslint@${{ matrix.eslint }} --legacy-peer-deps
          npx rimraf node_modules
        if: matrix.eslint != 8
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm test
